-- MySQL Script generated by MySQL Workbench
-- Sat Oct 16 02:10:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema groupomania
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `groupomania` ;

-- -----------------------------------------------------
-- Schema groupomania
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `groupomania` ;
USE `groupomania` ;

-- -----------------------------------------------------
-- Table `groupomania`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupomania`.`USERS` ;

CREATE TABLE IF NOT EXISTS `groupomania`.`USERS` (
  `idUSERS` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `role` TEXT NOT NULL,
  `isAdmin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUSERS`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupomania`.`COMMENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupomania`.`COMMENTS` ;

CREATE TABLE IF NOT EXISTS `groupomania`.`COMMENTS` (
  `idCOMMENTS` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(120) NOT NULL,
  `likes` INT UNSIGNED NULL DEFAULT 0,
  `USERS_idUSERS` INT NOT NULL,
  `POSTS_idPOSTS` INT NOT NULL,
  PRIMARY KEY (`idCOMMENTS`),
  INDEX `fk_COMMENTS_USERS1_idx` (`USERS_idUSERS` ASC) VISIBLE,
  INDEX `fk_COMMENTS_POSTS1_idx` (`POSTS_idPOSTS` ASC) VISIBLE,
  CONSTRAINT `fk_COMMENTS_USERS1`
    FOREIGN KEY (`USERS_idUSERS`)
    REFERENCES `mydb`.`USERS` (`idUSERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMMENTS_POSTS1`
    FOREIGN KEY (`POSTS_idPOSTS`)
    REFERENCES `mydb`.`POSTS` (`idPOSTS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupomania`.`POSTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupomania`.`POSTS` ;

CREATE TABLE IF NOT EXISTS `groupomania`.`POSTS` (
  `idPOSTS` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(50) NOT NULL,
  `attachement` VARCHAR(120) NULL,
  `likes` INT UNSIGNED NULL DEFAULT 0,
  `USERS_idUSERS` INT NOT NULL,
  PRIMARY KEY (`idPOSTS`),
  INDEX `fk_POSTS_USERS_idx` (`USERS_idUSERS` ASC) VISIBLE,
  CONSTRAINT `fk_POSTS_USERS`
    FOREIGN KEY (`USERS_idUSERS`)
    REFERENCES `mydb`.`USERS` (`idUSERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
